trigger:
  - main



variables:
  azureServiceConnection: 'arm-yuichimasuda'
  resourceGroupName: 'rg-bicep-pipeline'
  location: 'japaneast'
  templateNetworkFile: '02_network_demo/main.bicep'
  templateVmInitFile: '03_vm_demo/02_multiFiles/01_main_init.bicep'
  parametersVmInitFile: '03_vm_demo/02_multiFiles/parameter.bicepparam'

stages:
  - stage: Lint
    jobs:
      - job: LintBicep
        steps:
          - script: |
              az bicep build --file "$(templateNetworkFile)"
            displayName: 'Lint Network Bicep File'
          - script: |
              az bicep build --file "$(templateVmInitFile)"
            displayName: 'Lint VmInit Bicep File'

  - stage: Validate
    dependsOn: Lint
    jobs:
      - job: ValidateNetworkTemplate
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment group validate \
                  --resource-group "$(resourceGroupName)" \
                  --template-file "$(templateNetworkFile)"
      - job: ValidateVmInitTemplate
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment group validate \
                  --resource-group "$(resourceGroupName)" \
                  --template-file "$(templateVmInitFile)" \
                  --parameters "@$(parametersVmInitFile)"


  - stage: WhatIf
    dependsOn: Validate
    jobs:
      - job: WhatIfDeploymentNetwork
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment group what-if \
                  --resource-group "$(resourceGroupName)" \
                  --template-file "$(templateNetworkFile)"
      - job: WhatIfDeploymentVmInit
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment group what-if \
                  --resource-group "$(resourceGroupName)" \
                  --template-file "$(templateVmInitFile)" \
                  --parameters "@$(parametersVmInitFile)"


  - stage: Deploy
    dependsOn: WhatIf
    jobs:
      - job: DeployNetworkResources
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: $(azureServiceConnection)
              action: 'Create Or Update Resource Group'
              resourceGroupName: "$(resourceGroupName)"
              location: $(location)
              templateLocation: 'Linked artifact'
              csmFile: "$(templateNetworkFile)"
              deploymentMode: 'Incremental'
      - job: DeployVmInitResources
        dependsOn: DeployNetworkResources
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: $(azureServiceConnection)
              action: 'Create Or Update Resource Group'
              resourceGroupName: "$(resourceGroupName)"
              location: $(location)
              templateLocation: 'Linked artifact'
              csmFile: "$(templateVmInitFile)"
              csmParametersFile: "$(parametersVmInitFile)"
              deploymentMode: 'Incremental'
