name: Repository Dispatch Workflow
on:
  repository_dispatch:
    types: [echo_message]
jobs:
  echo_message:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Message
        run: echo "${{ github.event.client_payload.message }}"
